# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20160523_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ('user', 'data'), 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
