# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 13:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20160523_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.PositiveIntegerField(validators=django.core.validators.MinValueValidator(1)),
        ),
    ]
