# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=130)),
                ('slug', models.CharField(db_index=True, max_length=130, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='media/%Y/Ym/%d')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default='', max_length=1000)),
                ('multiplayer', models.BooleanField(default=False)),
                ('cooperation', models.BooleanField(default=False)),
                ('offline', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Gènero',
                'verbose_name_plural': 'Gêneros',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='shop.Genre'),
        ),
        migrations.AlterIndexTogether(
            name='game',
            index_together=set([('id', 'slug')]),
        ),
    ]
