# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('title',), 'verbose_name': 'Gênero', 'verbose_name_plural': 'Gêneros'},
        ),
        migrations.AddField(
            model_name='game',
            name='card',
            field=models.ImageField(blank=True, upload_to='/logos/%Y/Ym/%d'),
        ),
        migrations.AddField(
            model_name='game',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='game',
            name='specifications',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to='/%Y/Ym/%d'),
        ),
    ]
