# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160510_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='card',
            field=models.ImageField(blank=True, upload_to='/logos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to='/%Y/%m/%d'),
        ),
    ]
