# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_game_desconto'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Itens do Carrinho',
                'ordering': ('cart',),
                'verbose_name': 'Item do Carrinho',
            },
        ),
        migrations.RemoveField(
            model_name='cart',
            name='itens',
        ),
        migrations.AddField(
            model_name='item',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.Cart'),
        ),
        migrations.AddField(
            model_name='item',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Game'),
        ),
    ]
