# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthDate',
            field=models.DateField(default=datetime.datetime(2016, 5, 12, 17, 8, 12, 865215, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
