# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20160513_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthDate',
            field=models.DateField(),
        ),
    ]
