# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20160513_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fone',
            field=models.CharField(max_length=20),
        ),
    ]
