# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20160515_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_password_generated',
            field=models.BooleanField(default=False),
        ),
    ]
